-- =============================================================================
-- RESUTE — Modulo Financeiro: schema fin_*  (FASE 2 — AINDA NAO IMPLEMENTADO)
-- =============================================================================
-- Este arquivo e o ESPACO RESERVADO do banco do financeiro.
-- Nao ha nenhum comando ativo aqui: rodar este script hoje nao faz nada.
--
-- Quando o financeiro for construido, descomente/complete as tabelas abaixo
-- seguindo TODAS as regras desta secao. O proxy (api/secure-proxy.js) ja
-- aceita qualquer tabela com prefixo fin_ e ja exige filtro por empresa_id.
--
-- REGRAS OBRIGATORIAS PARA TODA TABELA fin_*:
--   1. coluna  empresa_id uuid not null references public.empresas(id) on delete cascade
--   2. indice  (empresa_id, <coluna de data principal>)
--   3. alter table ... enable row level security
--   4. policy de select restrita a empresa do usuario OU super_admin ativo
--      (copie o bloco de empresa_modulos_select em docs/supabase-modulos.sql)
--   5. insert/update/delete NUNCA expostos ao browser — service role no backend
--   6. script idempotente: create table if not exists / drop policy if exists
--
-- O prefixo fin_ nao e cosmetico: e ele que o allowlist do proxy usa
-- (FIN_TABLE_REGEX em api/secure-proxy.js). Tabela sem o prefixo e recusada.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- ESQUELETO SUGERIDO (comentado de proposito)
-- -----------------------------------------------------------------------------
--
-- create table if not exists public.fin_categorias (
--   id uuid primary key default gen_random_uuid(),
--   empresa_id uuid not null references public.empresas(id) on delete cascade,
--   nome text not null,
--   tipo text not null check (tipo in ('receita', 'despesa')),
--   ativo boolean not null default true,
--   criado_em timestamptz not null default now(),
--   unique (empresa_id, nome)
-- );
--
-- create table if not exists public.fin_lancamentos (
--   id uuid primary key default gen_random_uuid(),
--   empresa_id uuid not null references public.empresas(id) on delete cascade,
--   categoria_id uuid null references public.fin_categorias(id) on delete set null,
--   tipo text not null check (tipo in ('receita', 'despesa')),
--   descricao text null,
--   valor numeric(14,2) not null,
--   data_competencia date not null,
--   data_pagamento date null,
--   status text not null default 'previsto'
--     check (status in ('previsto', 'pago', 'atrasado', 'cancelado')),
--   origem text not null default 'manual' check (origem in ('manual', 'api')),
--   criado_em timestamptz not null default now()
-- );
-- create index if not exists fin_lancamentos_empresa_data_idx
--   on public.fin_lancamentos (empresa_id, data_competencia desc);
--
-- create table if not exists public.fin_contas_receber ( ... );
-- create table if not exists public.fin_contas_pagar   ( ... );
-- create table if not exists public.fin_fluxo_caixa    ( ... );
--
-- -- RLS de cada tabela acima (repetir o padrao):
-- -- alter table public.fin_lancamentos enable row level security;
-- -- drop policy if exists "fin_lancamentos_select" on public.fin_lancamentos;
-- -- create policy "fin_lancamentos_select" on public.fin_lancamentos
-- --   for select to authenticated
-- --   using (exists (select 1 from public.usuarios u
-- --                  where u.id = auth.uid() and u.ativo = true
-- --                    and (u.papel = 'super_admin'
-- --                         or u.empresa_id = public.fin_lancamentos.empresa_id)));
